version: 2
workflows:
  version: 2
  bratutils-flow:
    jobs:
      - test
      - tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^.*/

bratutils-env: &bratutils-env
  docker:
    - image: python:3.6.8-stretch
  working_directory: ~/project

jobs:
  test:
    <<: *bratutils-env
    steps:
      - checkout
      - run: make build
      - run: make lint
      - run: make test

  tag:
    <<: *bratutils-env
    steps:
      - checkout
      - run: make release
